/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.example.embeddingsencoderavro.schema;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class AvroEmbedding extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -6792515344949381163L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"AvroEmbedding\",\"namespace\":\"com.example.embeddingsencoderavro.schema\",\"fields\":[{\"name\":\"embedding_size\",\"type\":\"int\"},{\"name\":\"id\",\"type\":\"long\"},{\"name\":\"embedding\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"array\",\"items\":\"float\"}},\"default\":[]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<AvroEmbedding> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<AvroEmbedding> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<AvroEmbedding> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<AvroEmbedding> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<AvroEmbedding> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this AvroEmbedding to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a AvroEmbedding from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a AvroEmbedding instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static AvroEmbedding fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private int embedding_size;
  private long id;
  private java.util.List<java.util.List<java.lang.Float>> embedding;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public AvroEmbedding() {}

  /**
   * All-args constructor.
   * @param embedding_size The new value for embedding_size
   * @param id The new value for id
   * @param embedding The new value for embedding
   */
  public AvroEmbedding(java.lang.Integer embedding_size, java.lang.Long id, java.util.List<java.util.List<java.lang.Float>> embedding) {
    this.embedding_size = embedding_size;
    this.id = id;
    this.embedding = embedding;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return embedding_size;
    case 1: return id;
    case 2: return embedding;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: embedding_size = (java.lang.Integer)value$; break;
    case 1: id = (java.lang.Long)value$; break;
    case 2: embedding = (java.util.List<java.util.List<java.lang.Float>>)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'embedding_size' field.
   * @return The value of the 'embedding_size' field.
   */
  public int getEmbeddingSize() {
    return embedding_size;
  }


  /**
   * Sets the value of the 'embedding_size' field.
   * @param value the value to set.
   */
  public void setEmbeddingSize(int value) {
    this.embedding_size = value;
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public long getId() {
    return id;
  }


  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(long value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'embedding' field.
   * @return The value of the 'embedding' field.
   */
  public java.util.List<java.util.List<java.lang.Float>> getEmbedding() {
    return embedding;
  }


  /**
   * Sets the value of the 'embedding' field.
   * @param value the value to set.
   */
  public void setEmbedding(java.util.List<java.util.List<java.lang.Float>> value) {
    this.embedding = value;
  }

  /**
   * Creates a new AvroEmbedding RecordBuilder.
   * @return A new AvroEmbedding RecordBuilder
   */
  public static com.example.embeddingsencoderavro.schema.AvroEmbedding.Builder newBuilder() {
    return new com.example.embeddingsencoderavro.schema.AvroEmbedding.Builder();
  }

  /**
   * Creates a new AvroEmbedding RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new AvroEmbedding RecordBuilder
   */
  public static com.example.embeddingsencoderavro.schema.AvroEmbedding.Builder newBuilder(com.example.embeddingsencoderavro.schema.AvroEmbedding.Builder other) {
    if (other == null) {
      return new com.example.embeddingsencoderavro.schema.AvroEmbedding.Builder();
    } else {
      return new com.example.embeddingsencoderavro.schema.AvroEmbedding.Builder(other);
    }
  }

  /**
   * Creates a new AvroEmbedding RecordBuilder by copying an existing AvroEmbedding instance.
   * @param other The existing instance to copy.
   * @return A new AvroEmbedding RecordBuilder
   */
  public static com.example.embeddingsencoderavro.schema.AvroEmbedding.Builder newBuilder(com.example.embeddingsencoderavro.schema.AvroEmbedding other) {
    if (other == null) {
      return new com.example.embeddingsencoderavro.schema.AvroEmbedding.Builder();
    } else {
      return new com.example.embeddingsencoderavro.schema.AvroEmbedding.Builder(other);
    }
  }

  /**
   * RecordBuilder for AvroEmbedding instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<AvroEmbedding>
    implements org.apache.avro.data.RecordBuilder<AvroEmbedding> {

    private int embedding_size;
    private long id;
    private java.util.List<java.util.List<java.lang.Float>> embedding;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.example.embeddingsencoderavro.schema.AvroEmbedding.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.embedding_size)) {
        this.embedding_size = data().deepCopy(fields()[0].schema(), other.embedding_size);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.id)) {
        this.id = data().deepCopy(fields()[1].schema(), other.id);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.embedding)) {
        this.embedding = data().deepCopy(fields()[2].schema(), other.embedding);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing AvroEmbedding instance
     * @param other The existing instance to copy.
     */
    private Builder(com.example.embeddingsencoderavro.schema.AvroEmbedding other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.embedding_size)) {
        this.embedding_size = data().deepCopy(fields()[0].schema(), other.embedding_size);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.id)) {
        this.id = data().deepCopy(fields()[1].schema(), other.id);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.embedding)) {
        this.embedding = data().deepCopy(fields()[2].schema(), other.embedding);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'embedding_size' field.
      * @return The value.
      */
    public int getEmbeddingSize() {
      return embedding_size;
    }


    /**
      * Sets the value of the 'embedding_size' field.
      * @param value The value of 'embedding_size'.
      * @return This builder.
      */
    public com.example.embeddingsencoderavro.schema.AvroEmbedding.Builder setEmbeddingSize(int value) {
      validate(fields()[0], value);
      this.embedding_size = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'embedding_size' field has been set.
      * @return True if the 'embedding_size' field has been set, false otherwise.
      */
    public boolean hasEmbeddingSize() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'embedding_size' field.
      * @return This builder.
      */
    public com.example.embeddingsencoderavro.schema.AvroEmbedding.Builder clearEmbeddingSize() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public long getId() {
      return id;
    }


    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public com.example.embeddingsencoderavro.schema.AvroEmbedding.Builder setId(long value) {
      validate(fields()[1], value);
      this.id = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public com.example.embeddingsencoderavro.schema.AvroEmbedding.Builder clearId() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'embedding' field.
      * @return The value.
      */
    public java.util.List<java.util.List<java.lang.Float>> getEmbedding() {
      return embedding;
    }


    /**
      * Sets the value of the 'embedding' field.
      * @param value The value of 'embedding'.
      * @return This builder.
      */
    public com.example.embeddingsencoderavro.schema.AvroEmbedding.Builder setEmbedding(java.util.List<java.util.List<java.lang.Float>> value) {
      validate(fields()[2], value);
      this.embedding = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'embedding' field has been set.
      * @return True if the 'embedding' field has been set, false otherwise.
      */
    public boolean hasEmbedding() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'embedding' field.
      * @return This builder.
      */
    public com.example.embeddingsencoderavro.schema.AvroEmbedding.Builder clearEmbedding() {
      embedding = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public AvroEmbedding build() {
      try {
        AvroEmbedding record = new AvroEmbedding();
        record.embedding_size = fieldSetFlags()[0] ? this.embedding_size : (java.lang.Integer) defaultValue(fields()[0]);
        record.id = fieldSetFlags()[1] ? this.id : (java.lang.Long) defaultValue(fields()[1]);
        record.embedding = fieldSetFlags()[2] ? this.embedding : (java.util.List<java.util.List<java.lang.Float>>) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<AvroEmbedding>
    WRITER$ = (org.apache.avro.io.DatumWriter<AvroEmbedding>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<AvroEmbedding>
    READER$ = (org.apache.avro.io.DatumReader<AvroEmbedding>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeInt(this.embedding_size);

    out.writeLong(this.id);

    long size0 = this.embedding.size();
    out.writeArrayStart();
    out.setItemCount(size0);
    long actualSize0 = 0;
    for (java.util.List<java.lang.Float> e0: this.embedding) {
      actualSize0++;
      out.startItem();
      long size1 = e0.size();
      out.writeArrayStart();
      out.setItemCount(size1);
      long actualSize1 = 0;
      for (java.lang.Float e1: e0) {
        actualSize1++;
        out.startItem();
        out.writeFloat(e1);
      }
      out.writeArrayEnd();
      if (actualSize1 != size1)
        throw new java.util.ConcurrentModificationException("Array-size written was " + size1 + ", but element count was " + actualSize1 + ".");
    }
    out.writeArrayEnd();
    if (actualSize0 != size0)
      throw new java.util.ConcurrentModificationException("Array-size written was " + size0 + ", but element count was " + actualSize0 + ".");

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.embedding_size = in.readInt();

      this.id = in.readLong();

      long size0 = in.readArrayStart();
      java.util.List<java.util.List<java.lang.Float>> a0 = this.embedding;
      if (a0 == null) {
        a0 = new SpecificData.Array<java.util.List<java.lang.Float>>((int)size0, SCHEMA$.getField("embedding").schema());
        this.embedding = a0;
      } else a0.clear();
      SpecificData.Array<java.util.List<java.lang.Float>> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<java.util.List<java.lang.Float>>)a0 : null);
      for ( ; 0 < size0; size0 = in.arrayNext()) {
        for ( ; size0 != 0; size0--) {
          java.util.List<java.lang.Float> e0 = (ga0 != null ? ga0.peek() : null);
          long size1 = in.readArrayStart();
          java.util.List<java.lang.Float> a1 = e0;
          if (a1 == null) {
            a1 = new SpecificData.Array<java.lang.Float>((int)size1, SCHEMA$.getField("embedding").schema().getElementType());
            e0 = a1;
          } else a1.clear();
          SpecificData.Array<java.lang.Float> ga1 = (a1 instanceof SpecificData.Array ? (SpecificData.Array<java.lang.Float>)a1 : null);
          for ( ; 0 < size1; size1 = in.arrayNext()) {
            for ( ; size1 != 0; size1--) {
              java.lang.Float e1 = (ga1 != null ? ga1.peek() : null);
              e1 = in.readFloat();
              a1.add(e1);
            }
          }
          a0.add(e0);
        }
      }

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.embedding_size = in.readInt();
          break;

        case 1:
          this.id = in.readLong();
          break;

        case 2:
          long size0 = in.readArrayStart();
          java.util.List<java.util.List<java.lang.Float>> a0 = this.embedding;
          if (a0 == null) {
            a0 = new SpecificData.Array<java.util.List<java.lang.Float>>((int)size0, SCHEMA$.getField("embedding").schema());
            this.embedding = a0;
          } else a0.clear();
          SpecificData.Array<java.util.List<java.lang.Float>> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<java.util.List<java.lang.Float>>)a0 : null);
          for ( ; 0 < size0; size0 = in.arrayNext()) {
            for ( ; size0 != 0; size0--) {
              java.util.List<java.lang.Float> e0 = (ga0 != null ? ga0.peek() : null);
              long size1 = in.readArrayStart();
              java.util.List<java.lang.Float> a1 = e0;
              if (a1 == null) {
                a1 = new SpecificData.Array<java.lang.Float>((int)size1, SCHEMA$.getField("embedding").schema().getElementType());
                e0 = a1;
              } else a1.clear();
              SpecificData.Array<java.lang.Float> ga1 = (a1 instanceof SpecificData.Array ? (SpecificData.Array<java.lang.Float>)a1 : null);
              for ( ; 0 < size1; size1 = in.arrayNext()) {
                for ( ; size1 != 0; size1--) {
                  java.lang.Float e1 = (ga1 != null ? ga1.peek() : null);
                  e1 = in.readFloat();
                  a1.add(e1);
                }
              }
              a0.add(e0);
            }
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










